name: Cypress Tests

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: licenseplate
          MONGO_INITDB_ROOT_PASSWORD: licenseplate
          MONGO_INITDB_DATABASE: licenseplate 
        ports:
          - "27017:27017"

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Start Express App
        run: npm start &

      - name: Check Server Status
        id: server-status
        run: sleep 30s

      - name: Run Cypress Tests
        run: npm test
